forum/forum/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]
if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/main/urls.py
from django.urls import path
from .forms import UserLoginForm
from .views import index, create, profile_status
from .views import LoginView
from .views import profile
from .views import LogoutView
from .views import RegisterViews

from .views import delete

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('login/', LoginView.as_view(template_name='main/login.html', authentication_form=UserLoginForm), name='login'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/<str:status>', profile_status, name='profile_status'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterViews.as_view(), name='register'),
    path('accounts/create/', create, name='create'),
    path('accounts/delete/<pk>', delete, name='delete'),

]

forum/main/models.py
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.crypto import get_random_string


def get_name_file(instance, filename):
    return '/'.join([get_random_string(length=5) + ' ' + filename])


def validate_image_size(img):
    filesize = img.file.size
    megabyte_max = 2.0
    if filesize > megabyte_max * 1024 * 1024:
        raise ValidationError("Максимальный размер %sMB" % str(megabyte_max))


class AbsUser(AbstractUser):
    name = models.CharField(max_length=60, verbose_name='Имя', blank=False)
    surname = models.CharField(max_length=60, verbose_name='Фамилия', blank=False)
    patronymic = models.CharField(max_length=60, verbose_name='Отчество', blank=False)
    username = models.CharField(max_length=60, verbose_name='Логин', unique=True, blank=False)
    email = models.CharField(max_length=60, verbose_name='Почта', unique=True, blank=False)
    password = models.CharField(max_length=60, verbose_name='Пароль', unique=True, blank=False)
    role = models.CharField(max_length=60, verbose_name='Роль',
                            choices=(('admin', 'Администратор'), ('user', 'Пользователь')), default='user')
    personal_data = models.BooleanField(default=False, verbose_name='Согласие на обработку данных', blank=False)

    # USERNAME_FIELD = username

    def __str__(self):
        return str(self.name) + ' ' + str(self.surname) + ' (' + str(self.username) + ')'

    # class Meta(AbstractUser.Meta):
    #     pass


class Request(models.Model):
    STATUS_CHOICES = [
        ('new', 'новая'),
        ('work', 'принято в работу'),
        ('completed', 'выполнено')
    ]
    name = models.CharField(max_length=250, verbose_name='Имя', blank=False)
    description = models.CharField(max_length=250, verbose_name='Описание', blank=False)
    category = models.ForeignKey('Category', verbose_name='Категория', on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    photo = models.ImageField(upload_to=get_name_file,
                              validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp']),
                                          validate_image_size],
                              blank=False)
    status = models.CharField(max_length=60, verbose_name='Статус',
                              choices=(('new', 'новая'), ('work', 'принято в работу'), ('completed', 'выполнено')),
                              default='new', blank=False)
    user = models.ForeignKey('AbsUser', verbose_name='Заказчик', on_delete=models.CASCADE, null=True)
    comment = models.CharField(max_length=250, verbose_name='Комментрарий', blank=True, null=True)
    photo2 = models.ImageField(upload_to=get_name_file,
                               validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp']),
                                           validate_image_size],
                               blank=True, null=True)

    def __str__(self):
        return str(self.name) + ' ' + str(self.category)


class Category(models.Model):
    name = models.CharField(max_length=250, verbose_name='Имя', blank=False)

    def __str__(self):
        return str(self.name)

forum/main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.forms import TextInput

from .models import AbsUser, Request, Category


class RegisterUserForm(forms.ModelForm):
    surname = forms.CharField(label='Фамилия', widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': "Введите фамилию", 'id': "InputSurname", }),
                              validators=[RegexValidator('^[а-яА-Я- ]+$',
                                                         message='только кирилица и тире')],
                              error_messages={
                                  'required': 'Обязательное поле',
                              }, )
    name = forms.CharField(label='Имя',
                           validators=[RegexValidator('^[а-яА-Я- ]+$',
                                                      message='только кирилица и тире')],
                           error_messages={
                               'required': 'Обязательное поле',
                           }, widget=forms.TextInput(
            attrs={'class': "form-control", 'placeholder': "Введите имя", 'id': "InputName"}))
    patronymic = forms.CharField(label='Отчество',
                                 validators=[RegexValidator('^[а-яА-Я- ]+$',
                                                            message='только кирилица и тире')],
                                 error_messages={
                                     'required': 'Обязательное поле',
                                 }, widget=forms.TextInput(
            attrs={'class': "form-control", 'placeholder': "Введите отчество", 'id': "InputPatronymic"}))
    username = forms.CharField(label='Логин',
                               validators=[RegexValidator('^[a-zA-z-]+$',
                                                          message='только латиница и тире')],
                               error_messages={
                                   'required': 'Обязательное поле',
                                   'unique': 'Данный логин занят'
                               }, widget=forms.TextInput(
            attrs={'class': "form-control", 'placeholder': "Введите логин", 'id': "InputUsername"}))
    email = forms.EmailField(label='Почта',
                             error_messages={
                                 'required': 'Обязательное поле',
                                 'invalid': 'Не правильный формат',
                                 'unique': 'Адрес занят'
                             }, widget=forms.TextInput(
            attrs={'class': "form-control", 'placeholder': "Введите почту", 'id': "InputEmail"}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(
                                   attrs={'class': "form-control", 'placeholder': "Введите пароль",
                                          'id': "InputPassword"}),
                               error_messages={
                                   'required': 'Обязательное поле',
                               })
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput(
                                    attrs={'class': "form-control", 'placeholder': "Введите пароль",
                                           'id': "InputPassword2"}),
                                error_messages={
                                    'required': 'Обязательное поле',
                                })
    personal_data = forms.BooleanField(required=True, label='Согласие на обработку данных',
                                       error_messages={
                                           'required': 'Обязательно поле'
                                       })

    def clean(self):
        super().clean()
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password and password2 and password != password2:
            raise ValidationError({
                'password2': ValidationError('Пароли не совпадают', code='pass_error')
            })

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = AbsUser
        fields = ('surname', 'name', 'patronymic', 'username', 'email', 'password', 'password2', 'personal_data')


class CreateRequestForm(forms.ModelForm):
    photo = forms.ImageField(label='Фото')
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': "Введите название", 'id': "InputName"}))
    description = forms.CharField(widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': "Введите описание", 'id': "InputDescription"}))

    class Meta:
        model = Request
        fields = ('name', 'description', 'category', 'photo')
        enctype = "multipart/form-data"


class RequestForm(forms.ModelForm):
    def clean(self):
        status = self.cleaned_data.get('status')
        comment = self.cleaned_data.get('comment')
        photo2 = self.cleaned_data.get('photo2')
        if self.instance.status != 'new':
            raise forms.ValidationError({'status': 'Статус можно сменить только у нового заказа'})
        if status == 'work' and not comment:
            raise forms.ValidationError({'comment': 'Нужно ввести комментарий'})
        if status == 'completed' and not photo2:
            raise forms.ValidationError({'photo2': 'Нужно загрузить фото'})


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Введите логин', 'id': 'InputUsername'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control', 'placeholder': 'Введите пароль', 'id': 'InputPassword',
        }))

forum/main/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import RegisterUserForm, CreateRequestForm
from .models import Request, AbsUser


def index(request):
    counter = Request.objects.filter(status="work").all().count()
    rec = Request.objects.filter(status="completed").order_by('-date')[:4]
    return render(request, 'main/index.html', {'rec': rec, 'counter': counter})


@login_required
def profile(request):
    request_items = request.user.request_set.order_by('-date').all()
    return render(request, 'main/profile.html', context={'request_items': request_items})


def profile_status(request, status):
    request_items = request.user.request_set.filter(status=status).order_by('-date').all()
    return render(request, 'main/profile.html', context={'request_items': request_items, })


@login_required
def delete(request, pk):
    request = Request.objects.filter(user=request.user, pk=pk, status='new')
    if request:
        request.delete()
    return redirect('main:profile')


class LoginView(LoginView):
    template_name = 'main/login.html'


class LogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class RegisterViews(CreateView):
    template_name = 'main/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:login')


@login_required
def create(request):
    if request.method == 'POST':
        form = CreateRequestForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user_id = request.user.pk
            form.save()
            messages.warning(request, 'Заявка создана')
            return redirect('main:profile')
    else:
        form = CreateRequestForm(initial={'author': request.user})
    context = {'form': form}
    return render(request, 'main/create.html', context)

forum/main/templates/main/create.html
{% extends "layout/basic.html" %}

{% load static %}
{% load bootstrap4 %}

{% block title %} Создание заявки {% endblock %}

{% block content %}
   <h5 class="p-3 mb-1 font-weight-normal bg-dark text-white text-center">Создание заявки</h5>
   <form method="post" enctype="multipart/form-data">
       {{ form.non_field_errors }}
       {% csrf_token %}
       <div class="mb-3">
           <label for="InputName" class="form-label" >Название</label>
           {{ form.name }}
           {% if form.name.errors %} {{ form.name.errors }} {% endif %}
       </div>
       <div class="mb-3">
           <label for="InputDescription" class="form-label" >Описание</label>
           {{ form.description }}
           {% if form.description.errors %} {{ form.description.errors }} {% endif %}
       </div>
       <div class="mb-3">
        <label for="SelectCategory" class="form-label">Выберете категорию</label>
           {{form.category}}
           {% if form.category.errors %} {{ form.category.errors }} {% endif %}
       </div>
       <div class="mb-3 ">
           <p>Загрузите Фото</p>
           {{ form.photo}}
           {% if form.photo.errors %} {{ form.photo.errors }} {% endif %}
       </div>
       <button class="btn btn-dark mt-4 mb-2" type="submit">Создать заявку</button>
   </form>
<script>
    let sel = document.querySelector('#id_category');
    sel.classList.add('form-control');
</script>
{% endblock %}

forum/main/templates/main/index.html
{% extends "layout/basic.html" %}

{% load static %}
{% load bootstrap4 %}

{% block content %}
   <h5 class="p-3 mb-1 font-weight-normal bg-dark text-white text-center">Заявок в работе: {{ counter }}</h5>
        {% for item in rec %}
            <div class="d-flex p-3 mb-2 text-dark bg-light">
                <img class="col-4" src="{{ item.photo.url }}" alt="Фото заявки">
                <p class="p-3 mb-2"><b>Наименование:</b> {{ item.name }} <br> <b>Категория:</b> {{ item.category }}
                    <br> <b>Дата добавления:</b> {{ item.date }} <br> <b>Описание:</b> {{ item.description }}
                    <br><b>Статус:</b>{{ item.status_verbose }}</p>
            </div>
   {% endfor %}
{% endblock %}

forum/main/templates/main/login.html
{% extends "layout/basic.html" %}

{% load static %}
{% load bootstrap4 %}

{% block title %} Вход {% endblock %}

{% block content %}
   <h5 class="p-3 mb-1 font-weight-normal bg-dark text-white text-center">Вход</h5>
   {% if user.is_authenticated %}
       <p>Вы уже выполнили вход.</p>
   {% else %}
       <form method="post">
           {{ form.non_field_errors }}
           {% csrf_token %}
                <div class="mb-3">
                    <label for="InputUsername" class="form-label">Логин</label>
                    {{form.username}}
                    {% if form.username.errors %} {{ form.username.errors }} {% endif %}
                </div>
                <div class="mb-3">
                    <label for="InputPassword" class="form-label">Пароль</label>
                    {{form.password}}
                    {% if form.password.errors %} {{ form.password.errors }} {% endif %}
                </div>
                <button class="btn btn-dark mt-4 mb-2" type="submit">Войти</button>

       </form>
   {% endif %}
{% endblock %}

forum/main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% load static %}
{% load bootstrap4 %}

{% block title %} Выход {% endblock %}

{% block content %}
   <h5 class="p-3 mb-1 font-weight-normal bg-dark text-white text-center">Выход</h5>
   <div class="d-flex p-3 mb-2 text-dark bg-light">
      <p class="p-3 mb-2">Вы успешно вышли с сайта.</p>
   </div>
{% endblock %}

forum/main/templates/main/profile.html
{% extends 'layout/basic.html' %}

{% load static %}
{% load bootstrap4 %}

{% block title %} Профиль {% endblock %}
{% block content %}
    <h5 class="p-3 mb-1 font-weight-normal bg-dark text-white text-center">Ваши заявки</h5>
    <div class="d-flex p-1 mb-1 justify-content-around bg-dark ">
        <a class="h-100 text-white" href="{% url 'main:profile_status' status='new'%}">Новые</a>
        <a class="h-100 text-white" href="{% url 'main:profile_status' status='work'%}">В работе</a>
        <a class="h-100 text-white" href="{% url 'main:profile_status' status='completed' %}">Готовые</a>
        <a class="h-100 text-white" href="{% url 'main:profile'%}">Все</a>
    </div>
    {% if request_items %}
        {% for item in request_items %}
            <div class="d-flex p-3 mb-2 text-dark bg-light">
                <img class="col-4" src="{{ item.photo.url }}" alt="Фото заявки">
                <p class="p-3 mb-2"><b>Наименование:</b> {{ item.name }} <br> <b>Категория:</b> {{ item.category }}
                    <br> <b>Дата добавления:</b> {{ item.date }} <br> <b>Описание:</b> {{ item.description }}
                    <br><b>Статус:</b>{{ item.status }}</p>

                {% if item.status == 'new' %}
                    <button type="button" class="btn-outline-danger ml-auto h-100 p-1" onclick='del(this,{{ item.pk }})'>Удалить</button>
                    <a class="delButton ml-auto" hidden="true" href="{% url 'main:delete' item.pk %}">
                        <button type="button" class=" btn-outline-danger " >Нажми, если уверен</button>
                    </a>
                {% endif %}
            </div>
        {% endfor %}
                    <script>
                        del = (target, pk) =>{
                           let targButton = target;
                           let delButton = target.nextElementSibling;
                           console.log(delButton);
                           targButton.hidden = true;
                           delButton.hidden = false;
                           setTimeout(() => {
                                delButton.hidden = true;
                                targButton.hidden = false;
                                }, 2000);
                        }
                    </script>
    {% else %}
        <p class="mt-3">Заявки отсутствуют</p>
    {% endif %}
{% endblock %}

forum/main/templates/main/register.html
{% extends "layout/basic.html" %}

{% load static %}
{% load bootstrap4 %}

{% block title %} Регистрация {% endblock %}

{% block content %}
   <h5 class="p-3 mb-1 font-weight-normal bg-dark text-white text-center">Регистрация</h5>
   <form method="post">
       {{ form.non_field_errors }}
       {% csrf_token %}
                    {{form.birth_year}}
                <div class="mb-3">
                    <label for="InputSurname" class="form-label">Фамилия</label>
                    {{ form.surname }}
                    {% if form.surname.errors %} {{ form.surname.errors }} {% endif %}
                </div>
                <div class="mb-3">
                    <label for="InputDescription" class="form-label">Имя</label>
                    {{ form.name }}
                    {% if form.name.errors %} {{ form.name.errors }} {% endif %}
                </div>
                <div class="mb-3">
                    <label for="InputPatronymic" class="form-label">Отчество</label>
                    {{ form.patronymic }}
                    {% if form.patronymic.errors %} {{ form.patronymic.errors }} {% endif %}
                </div>
                <div class="mb-3">
                    <label for="InputUsername" class="form-label">Логин</label>
                    {{ form.username }}
                    {% if form.username.errors %} {{ form.username.errors }} {% endif %}
                </div>
                <div class="mb-3">
                    <label for="InputEmail" class="form-label">Почта</label>
                    {{ form.email }}
                    {% if form.email.errors %} {{ form.email.errors }} {% endif %}
                </div>
                <div class="mb-3">
                    <label for="InputPassword" class="form-label">Пароль</label>
                    {{ form.password }}
                    {% if form.password.errors %} {{ form.password.errors }} {% endif %}
                </div>
                <div class="mb-3">
                    <label for="InputPassword2" class="form-label">Пароль (повторно)</label>
                    {{ form.password2 }}
                    {% if form.password2.errors %} {{ form.password2.errors }} {% endif %}
                </div>
                <div class="mb-3">
                        Согласие на обработку данных
                    {{ form.personal_data }}
                    {% if form.personal_data.errors %} {{ form.personal_data.errors }} {% endif %}
                </div>
                <button class="btn btn-dark mt-4 mb-2" type="submit">Зарегистрироваться</button>
   </form>
{% endblock %}